### ISSUE TITLE
Running in "both" mode only processes the "proposer" thread but not the "collator" thread

### ISSUE THREAD

**Issue by ltfschoen** [Drops-of-Diamond/Diamond-drops#16]
In the 'collator' branch when I run in "Both" Mode, it only shows it processing the "Proposer" thread being joined, but not also the Collator thread. It doesn’t appear to process the Collator part on [Line 70](https://github.com/Drops-of-Diamond/diamond_drops/pull/14/files#diff-b4aea3e418ccdb71239b96952d9cddb6R70)

**Comment by ChosunOne** [comment]
join is a blocking operation, it waits for the thread to end.  These last two lines only exist to make sure both threads are running.  The threads start running at the spawn command.  It isn't necessary for Line 70 to be run, only that main doesn't exit before both threads have finished.
