### ISSUE TITLE
Integration tests are not being included with default test command

### ISSUE THREAD

**Issue by ltfschoen** [Drops-of-Diamond/Diamond-drops#17]
In the 'collator' branch, when I run the tests with `cargo test` it does not picking up and run the tests that are in the tests/ directory anymore. It only runs the new tests that are within the implementation files. So to run all tests at the moment we have to run `cargo test --test cli_test && cargo test` instead of just `cargo test`, which is not ideal

**Comment by jamesray1** [comment]
Closing as `cargo test` does now run all tests including integration tests.
