### ISSUE TITLE
Investigate possibility to improve conversion of ethereum_types::U256 to u8 byte array

### ISSUE THREAD

**Issue by ltfschoen** [Drops-of-Diamond/Diamond-drops#21]
Reference to code: https://github.com/Drops-of-Diamond/diamond_drops/blob/notary/src/collation/header.rs#L75

```rust
// A crude way of converting the ethereum_types::U256 to a u8 byte array to be hashed.  Suggestions to improve this are desired. 
fn u256_to_bytes32(u256: ethereum_types::U256, dst: &mut [u8; 32]) {
    for i in 0..32 {
        dst[i] = u256.byte(i);
    }
}
```

**Comment by jamesray1** [comment]
One improvement that I think it needs is to return dst, and not actually take dst as an input parameter.

**Comment by ChosunOne** [comment]
Yeah, if I can figure out a way to do that with the Rust ownership and lifetime rules I'll change it.

**Comment by ltfschoen** [comment]
Yeh I'll create a PR

Reference: https://doc.rust-lang.org/book/second-edition/ch10-03-lifetime-syntax.html

**Comment by ChosunOne** [comment]
Ok I've just pushed an update to make this return the bytes array instead of requiring two inputs.  Further improvements are welcome

**Comment by ltfschoen** [comment]
Ok, I made changes to use lifetimes but I think your changes are better. If there's only one parameter for the function then we shouldn't need lifetimes anymore. Here are the changes I was going to make for your reference, they were just straight from the documentation. https://github.com/Drops-of-Diamond/diamond_drops/compare/notary...ltfschoen:notary?expand=1
```rust
let mut sid: &mut [u8; 32] = &mut [0; 32]; 
u256_to_bytes32(&self.shard_id, &mut sid);

...

let mut p: &mut [u8; 32] = &mut [0; 32];
u256_to_bytes32(&self.period, &mut p);

...

fn u256_to_bytes32<'a>(u256: &'a ethereum_types::U256, dst: &'a mut [u8; 32]) -> &'a [u8; 32] {
    for i in 0..32 {
        dst[i] = u256.byte(i);
    }
    dst
}

...

let mut sid_bytes: &mut [u8; 32] = &mut [0; 32];
u256_to_bytes32(&sid, &mut sid_bytes);

...

let mut period_bytes: &mut [u8; 32] = &mut [0; 32];
u256_to_bytes32(&period, &mut period_bytes);
```

**Comment by jamesray1** [comment]
Looks good now. I'll close this for now.
