### ISSUE TITLE
Blob serialisation

### ISSUE THREAD

**Issue by jamesray1** [Drops-of-Diamond/Diamond-drops#35]
https://ethresear.ch/t/blob-serialisation/1705

**Comment by jamesray1** [comment]
https://github.com/ethereum/py-evm/pull/555/files

**Comment by jamesray1** [comment]
#46

**Comment by ltfschoen** [comment]
Note the following link includes GoLang implementation of Blob serialization progress https://github.com/prysmaticlabs/geth-sharding/pull/92

**Comment by jamesray1** [comment]
#65.
