### ISSUE TITLE
Add support to open UML diagram in different browsers and OSs other than Mac

### ISSUE THREAD

**Issue by ltfschoen** [Drops-of-Diamond/Diamond-drops#48]
See https://github.com/Drops-of-Diamond/diamond_drops/pull/47.
Currently we have only supported `cargo make` in the Makefile.toml to run the command that opens the diagram in Google Chrome. Add tasks that open it in different browsers including Firefox

**Comment by jamesray1** [comment]
I can't take a screenshot of it now, the screenshot just shows a blank box. It has always had the text spilling over the boxes, including now.

Most other browsers are Chromium, e.g. Brave and Opera, but not Safari.

When I look in Brave it looks fine (no spilling).

**Comment by ltfschoen** [comment]
That's strange. When I run `cargo make uml-chrome` it opens in Google Chrome. When I run `cargo make uml-firefox` it opens in Firefox, when I run `cargo make uml-brave` it opens in Brave. Note that the task runner makes sure to clean and build before generating the UML diagram and displaying it.
Also, when I run `cargo make docs` it shows the UML diagram correctly in the diamond-drops-node section.
What command are you running that's causing it to not show the UML diagram correctly?

**Comment by jamesray1** [comment]
I wasn't running any command, just looking at the readme in Firefox on Linux, every time the text spills over the borders. Oh I accidentally closed this.

**Comment by jamesray1** [comment]
Luke feel free to ignore all these messages while you're away, I'll deal with it.


```
$ inkscape ./diagrams/ml.svg

(inkscape:27274): Gtk-WARNING **: 19:37:54.909: Unable to locate theme engine in module_path: "murrine",

(inkscape:27274): Gtk-WARNING **: 19:37:54.910: Unable to locate theme engine in module_path: "murrine",

(inkscape:27274): Gtk-WARNING **: 19:37:54.910: Unable to locate theme engine in module_path: "murrine",
./diagrams/ml.svg:1: parser error : Document is empty
```

`firefox ./diagrams/ml.svg` opens a new tab with 
```
XML Parsing Error: no root element found
Location: file:///home/james/dod/diagrams/ml.svg
Line Number 1, Column 1:
^
```

With the following task I get `./diagrams/ml.svg:1: parser error : Document is empty` on the last line of the output.
```
[tasks.uml-inkscape-linux]
command = "inkscape"
args = ["./diagrams/ml.svg"]
dependencies = ["build"]
```

With `cargo make uml-firefox-linux` the same happened as with `firefox ./diagrams/ml.svg`.

```
[tasks.uml-chrome-linux]
command = "linux"
args = ["./diagrams/ml.svg"]
dependencies = ["build"]
```

**Comment by jamesray1** [comment]
I'll try `xdg-open`. https://superuser.com/questions/38984/linux-equivalent-command-for-open-command-on-mac-windows

**Comment by jamesray1** [comment]
`xdg-open ./diagrams/ml.svg` doesn't work on fresh installs of Manjaro on my laptop (opens with Libre Office with an error) and desktop (opens in Visual Studio) as well as with Ubuntu (opens it in a text editor.

Given that this issue is not a high priority I'll come back to it another time.

**Comment by jamesray1** [comment]
https://github.com/Drops-of-Diamond/diamond_drops/pull/57

**Comment by jamesray1** [comment]
So I can download and open https://www.svgstudio.com/pages/free-sample and view it as expected, but if I try to open ml.svg in the same way or from any application it is just an empty file.

I installed python-pygraphviz and ran `cargo make`, and I can now open the file.

**Comment by jamesray1** [comment]
OK https://github.com/Drops-of-Diamond/diamond_drops/pull/67 fixes this.
